apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1Ea3hOakV3TWpreU0xb1hEVE15TURreE16RXdNamt5TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT0tKCkxzNW9ONWhQVkZ1QUhsZkdMeTU4QmNrM2pLQVhLMUluRENEYnBRMHBnNVlLV2VHR3l1R0hmeEE3eWxOK1pnd3MKemlxSVNpVWVIWHJRL0M3Kzgwb2o2aEtEYllDd1NJL3F1SmZScFR1TTFrOHhMejRHWWZqWU1RM0FJb0lvdS80NwprQUZjanR5NjN2Si9Mb2RmRWZ4OWp6T2FRd1FnYnBUTnB2elR2RjhPWk1zeFlXeGFWdkxiSGlEVW15d2VQQUI3CmNxUnBzTXY1Z2gvZXdmZ0FvYUMrRVhiMVZZazBTTVBkWHpxOFM4RHRNTG1mWWZSQ2ZzT2kzQjcwVmlGWDRLcVcKdG1xSldaRXlLSFYrbkhaODc3UGJETExtZ1pGRVltM0hmbkpSUXRKWHdzK2RzMnlFN0s3RC9OMFNQUURxZitLVgpJdCs3UDZhSHpxdFBJd3VGbXBNQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCNXJtOXV6ODN4MkcrblZoajNmSCtCMWxZRDRNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS0IzL2JKYjdRRjRYcVhFb09aNApnS3VhVGJFTnVtZU5QVllxZlkzbUlSbmVmS2tRNFFXNEV6UXI1TmUyYjFmcHBBcmQvSDBMRHMxMUVwaTBUd2p6CndtVldhNDhoS2IvLy9UTzdZYXZmZmFSV3hyZDN2UUlZOXhEaHdGUU1MK2pISERKVFZsQVNWRE1rSlVDMTdsNzcKWlN6a05ZQytJYllKSHpGR291Z0UyYncwaFJGaFlMQmpveE5zS00raWdEL2x6SUovU3dCcWFTZTZDSzlsQmQyZgp0dmNsZHZHT3ljb2EwUFY4U2Z1K2pjNjBiSDd6bjFVdk5oWWQrR0lwNlpPT2EvcmYyUjhGN3dNQmpnNnFJRkJNCnVHRWIydW1FQnRrZ2N6UVlyZk5wVEhUY0xjZzc1YjdhbHZPOVRac1pOeldSOElSNjUrUzFHWUhHdGg4Z2czTXgKb1VnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://0732E221F6871632BB43959CD1F09867.gr7.us-east-2.eks.amazonaws.com
  name: microserver-udagram.us-east-2.eksctl.io
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1Ea3hOakE1TVRBeE9Wb1hEVE15TURreE16QTVNVEF4T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTcyClM4S3U3dkhMQTN5QURudWNlK3R4K3JQd01hL2VwemlHVHgwVmNXaS81UTBKUEZHWkdwZWFQU2w0UDVNNEVrN1kKc0d4OHVLbXBSMjVLakJBRnY5R2JkcFc3OVNyaFBTb3MwZWNJcGZ5NFpXQjlzVURBR1hrVmFLSlgxTEdscDR6RQpRcGVQK2Q2YkxhY0xGQUQ2QjVhbitoZ0VDZlVVQlJWcm9USGYxUTNaNFVQTGY0S0V5d0ZDUUlrMXhpbmZtN2RmClY2Yit2VFcrczdoK052a1lmckQxQmhIbEdPYzZVbVlFWmMyc0hIbVBOcjFzSVpUbStkMjBMQTR6ZU5UVjg2KzgKV245d1QrdHVyY1lxR1NiT3Z0bXJBOHFGcHE2Q2l1eDgzNEZxSkE3djBTc2toVXFSRmpsY3JuSFYyeWpMZVM1awowWWI5ZVZucDlLaytvRGZtdkFVQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZPajVZRU5BQnY3Z1FBSnZYak0rcEh5a1ZvczJNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBR2swSkxWWTQwMHNpdEhDWGNzVAplZjlIVXJoSjI4UzJqVnRKNXlZeXg2NlMwajd5MmtaN0p1SnlBaTRINzh1M2tBWkw5a0xEbkcyZ2tTNFZnODFICkxZVFc3UDVUVXI3aG1IUFUyR1cyVVRIR3JDbk1VTlJuT0phMmpsNCs0cGpRQnp3bS9xekFKL0pzb1NaNjFpcWwKRDFEZTZGVEFvZXc3UTFLWU1UTjUwQXpaVHlsL2hZdHVTRU12anlGS3kwN2ZZbWF4QTlWL3BxUjlXQjlLSVJ5YQp3d1BEU201eDZMRm5RWkNVNzJDSWxLWm5ZelorVVhOdW54MUZXQitLRCtjZmhmeE1JdWpENDJoU3VnaEVjdjFZCkpTemVxa0dUbWNYYUV2ZzRoajZBbUZ4cmpBS2NKcEkvYjBUNWNuUFVDOURlY0ZhQkVKMHlWWWl0VXF3Y2dPejYKZEtBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://8B8715FE65A15B2AC64DC2513FA70553.gr7.us-east-1.eks.amazonaws.com
  name: myCluster.us-east-1.eksctl.io
contexts:
- context:
    cluster: microserver-udagram.us-east-2.eksctl.io
    user: smart@microserver-udagram.us-east-2.eksctl.io
  name: smart@microserver-udagram.us-east-2.eksctl.io
- context:
    cluster: myCluster.us-east-1.eksctl.io
    user: smart@myCluster.us-east-1.eksctl.io
  name: smart@myCluster.us-east-1.eksctl.io
current-context: smart@microserver-udagram.us-east-2.eksctl.io
kind: Config
preferences: {}
users:
- name: smart@microserver-udagram.us-east-2.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --cluster-name
      - microserver-udagram
      - --region
      - us-east-2
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
- name: smart@myCluster.us-east-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - eks
      - get-token
      - --cluster-name
      - myCluster
      - --region
      - us-east-1
      command: aws
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      provideClusterInfo: false
